version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-pipeline-local"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bakl0wn5u4p"
s3_prefix = "sam-pipeline-local"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
