version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::480640902392:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-5Q2ULMC6CIBW"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::480640902392:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1QCEAD90NLAFZ"
cloudformation_execution_role = "arn:aws:iam::480640902392:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-134013ITFXA7N"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1c3gydghor0v9"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::480640902392:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-ZAOJDIXFRZTV"
cloudformation_execution_role = "arn:aws:iam::480640902392:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1Q00J38MQWLR9"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-okbhnx1nrcji"
image_repository = ""
region = "us-east-1"
